# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/6b49c95a-8578-4829-849a-e7c27ab187b5";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/FCC6-2BA6";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/ssd_m2" =
    { device = "/dev/disk/by-uuid/C2EE0161EE014EDB";
      fsType = "ntfs";
    };

  fileSystems."/mnt/ssd_100gb" =
    { device = "/dev/disk/by-uuid/22B44ADAB44AAFD9";
      fsType = "ntfs";
    };

  fileSystems."/mnt/hdd_2tb" =
    { device = "/dev/disk/by-uuid/9E5A58535A5829F3";
      fsType = "ntfs";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/a775c887-26fd-45cf-9f15-3869f87f8398"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
